version: '3.8'

services:
  retailapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retailapi
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8088}:${APP_PORT:-8088}"
    restart: always